//
//  DataService.swift
//  Hues and Clues
//
//  Created by Daniel Coyle on 3/20/24.
//

import Foundation
import SwiftUI

struct DataService {
    func getClues() -> [String:String] {
        return [// A Section
                "Leather briefcase":"a1",
                "Mahogany desk":"a1",
                "Cocoa beans":"a1",
                "Chestnut horse":"a1",
                "Dark chocolate":"a1",
                "Red Wine":"a2",
                "Ruby Gemstone":"a2",
                "Cherry Stem":"a2",
                "Blood":"a2",
                "Red Rose":"a3",
                "Apple":"a3",
                "Cranberry":"a3",
                "Cardinal (bird)":"a3",
                "Brick":"a3",
                "Fire Hydrant":"a4",
                "Red Velvet Cake":"a4",
                "Tomato":"a4",
                "Red Chili Pepper":"a4",
                "Ladybug":"a4",
                "Fire Truck":"a5",
                "Red Bell Pepper":"a5",
                "Tulip flower":"a5",
                "Emergency Exit Sign":"a5",
                "Coca-Cola Can":"a5",
                "Fresh Strawberry":"a6",
                "Ferrari Sports Car":"a6",
                "Valentine's Day Heart":"a6",
                "Ripe Cherry":"a6",
                "Rose Petals":"a6",
                "Raspberry":"a7",
                "Red Cherry Blossom":"a7",
                "Watermelon Flesh":"a7",
                "Red Silk Fabric":"a7",
                "Strawberry Ice Cream":"a8",
                "Pink Tulip":"a8",
                "Strawberry sorbet":"a8",
                "Fuchsia flower":"a9",
                "Magenta Ribbon":"a9",
                "Bougainvillea flower":"a9",
                "Flowering raspberry":"a9",
                "Barbie Doll Dress":"a9",
                "Magenta silk scarf":"a10",
                "Purple orchid":"a10",
                "Pink sapphire gemstone":"a10",
                "Magenta sunset":"a10",
                "Violet sunset":"a11",
                "Purple aurora borealis":"a11",
                "Purple onion":"a11",
                "Violet butterfly":"a11",
                "Grape soda can":"a11",
                "Purple grapes":"a12",
                "Purple cabbage":"a12",
                "Purple iris":"a12",
                "Purple figs":"a12",
                "Purple octopus":"a12",
                "Grape hyacinth flowers":"a13",
                "Violet (flower)":"a13",
                "Purple hydrangea flowers":"a13",
                "Grape juice":"a14",
                "Lavender essential oil":"a14",
                "Concord grape jelly":"a14",
                "Violet flower bouquet":"a14",
                "Violet silk scarf":"a14",
                
                // B Section
                "Potato":"b1",
                "Leather Jacket":"b1",
                "Rustic wooden table":"b1",
                "Cinnamon Sticks":"b1",
                "Walnut":"b1",
                "Oak tree bark":"b1",
                "Terracotta pottery":"b1",
                "Milk Chocolate":"b1",
                "Rusty Iron":"b2",
                "Chestnut":"b2",
                "Brick wall":"b2",
                "Copper cookware":"b2",
                "Mahogany wood":"b2",
                "Autumn leaves":"b2",
                "Rubber Band":"b2",
                "Unsweet Tea":"b2",
                "Eggplant parmesan":"b3",
                "Traffic cone":"b3",
                "Tangerine":"b3",
                "Pumpkin":"b3",
                "Marigold flower":"b3",
                "Sweet potato":"b3",
                "Carrot":"b3",
                "Basketball":"b3",
                "Stop sign":"b4",
                "Cherry":"b4",
                "Mars":"b4",
                "Raspberry sorbet":"b5",
                "Red tulip":"b5",
                "Pink Tourmaline gemstone":"b6",
                "Tongue":"b6",
                "Pink Rose":"b6",
                "Pink Lemonade":"b6",
                "Flamingo":"b6",
                "Strawberry milkshake":"b6",
                "Strawberry yogurt":"b6",
                "Pink sapphire":"b7",
                "Pink rose petals":"b7",
                "Magenta silk fabric":"b8",
                "Peony Flower":"b8",
                "Bubblegum":"b8",
                "Pink diamond":"b8",
                "Orchid blooms":"b8",
                "Conch shell":"b8",
                "Rhododendron flowers":"b9",
                "Magenta lipstick":"b9",
                "Bougainvillea flowers":"b10",
                "Beetroot":"b10",
                "Violet glass beads":"b10",
                "Barney":"b10",
                "Purple velvet fabric":"b11",
                "Purple sweet potatoes":"b11",
                "Purple jelly beans":"b12",
                "Violet fabric":"b12",
                "Royal purple robe":"b13",
                "Lavender flower":"b13",
                "Purple pansy":"b14",
                "Aubergine":"b14",
                "Eggplant":"b14",
                "Amethyst gemstone":"b14",
                
                // C Section
                "Sunflower":"c1",
                "Lemon Skin":"c1",
                "Squash":"c1",
                "Taxi":"c1",
                "Pineapple":"c2",
                "Daisy (flower)":"c2",
                "Banana":"c2",
                "Saturn":"c2",
                "Sandcastle":"c2",
                "Orange Tabby cat":"c3",
                "Monarch butterfly":"c3",
                "Orange Sunset":"c3",
                "Orange Popsicle":"c3",
                "Persimmon":"c3",
                "Apricot":"c4",
                "Peach":"c4",
                "Orange creamsicle":"c4",
                "Papaya":"c4",
                "Ballet Shoes":"c5",
                "Strawberry macaron":"c5",
                "Himalayan salt":"c5",
                "Pink coral":"c5",
                "Pink champagne":"c5",
                "Shrimp":"c5",
                "Himalayan salt lamp":"c6",
                "Pink satin ribbon":"c6",
                "Pink Macarons":"c6",
                "Pink tulips":"c6",
                "Cherry Blossom":"c7",
                "Pink marshmallows":"c7",
                "Rose quartz gemstone":"c7",
                "Pink carnation":"c7",
                "Cotton Candy":"c7",
                "Jelly Fish":"c7",
                "Conch pearls":"c7",
                "Orchid Mantis":"c7",
                "Pink Pearl":"c8",
                "Cotton candy machine":"c8",
                "Carnation flower":"c9",
                "Hydrangea petals":"c10",
                "Lavender flowers":"c10",
                "Violet flowers":"c10",
                "Purple crayon":"c10",
                "Violet":"c10",
                "Purple Orchid Mantis":"c11",
                "Purple glass vase":"c12",
                "Fig":"c12",
                "Indigo dye":"c13",
                "Indigo ink":"c13",
                "Dark blue ink":"c14",
                "Sapphire gemstone":"c14",
                "Blue velvet fabric":"c14",
                "Midnight sky":"c14",
                "Deep ocean":"c14",
                "Blue jay feather":"c14",
                "Tanzanite":"c14",
                
                // D Section
                "Corn":"d1",
                "Canary bird":"d1",
                "Rubber Duck":"d1",
                "Highlighter":"d1",
                "Lemon":"d1",
                "Buttercup flower":"d1",
                "The Sun":"d1",
                "Daffodil":"d2",
                "School Bus":"d2",
                "Olive Oil":"d2",
                "Star":"d2",
                "Tennis Ball":"d2",
                "Raincoat":"d2",
                "Yellow-green pear":"d3",
                "Yellow-green chartreuse":"d3",
                "Lemonade":"d4",
                "Pale yellow macaron":"d4",
                "Buttercream frosting":"d4",
                "Caterpillar":"d5",
                "Green grapes":"d5",
                "Green tea":"d5",
                "Green apple":"d5",
                "Cucumber Inside":"d5",
                "Green olives":"d5",
                "Lime Inside":"d6",
                "Celery stalk":"d6",
                "Mint Ice Cream":"d6",
                "Chartreuse cocktail":"d6",
                "Green sea glass":"d7",
                "Emerald gemstone":"d7",
                "Wasabi":"d7",
                "Shamrock":"d7",
                "Aqua glass vase":"d8",
                "Turquoise ocean water":"d8",
                "Light teal scarf":"d9",
                "Aquamarine gemstone":"d9",
                "Light teal throw pillow":"d9",
                "Daytime Sky":"d10",
                "Bright cyan marker":"d10",
                "Icebergs":"d10",
                "Double Blue Diamond":"d11",
                "Caribbean sea":"d11",
                "Blue jay bird":"d12",
                "Blue Lightsaber":"d12",
                "Turquoise feather":"d12",
                "Neon tetras":"d12",
                "Dory (Finding Nemo)":"d13",
                "Forget-Me-Not flowers":"d13",
                "Denim jeans":"d14",
                "Blue whale":"d14",
                "Blueberry":"d14",
                "Delphiniums":"d14",
                
                // E Section
                "Green algae":"e1",
                "Shrek":"e1",
                "Grasshopper":"e2",
                "Mint leaf":"e3",
                "Jade sculpture":"e3",
                "Freshly Mown Grass":"e3",
                "Turtle":"e4",
                "Spinach leaves":"e4",
                "Green beans":"e4",
                "Grass":"e5",
                "Cucumber Skin":"e5",
                "Green Bell Pepper":"e5",
                "Moss":"e5",
                "Broccoli Head":"e5",
                "Okra":"e5",
                "Wreath":"e6",
                "Lime Skin":"e6",
                "Watermelon Skin":"e6",
                "Chameleon":"e7",
                "Jade plant":"e7",
                "Green Lightsaber":"e7",
                "Green tea leaves":"e7",
                "Mountain Dew":"e8",
                "Emerald":"e8",
                "Parsley":"e8",
                "Frog":"e8",
                "Kiwi":"e9",
                "Green peas":"e9",
                "Avocado":"e9",
                "Asparagus":"e9",
                "Pistachio":"e10",
                "Lettuce":"e10",
                "Leaves":"e10",
                "Lime Sherbet":"e10",
                "Broccoli Stem":"e10",
                "Mint":"e11",
                "Chlorophyll":"e11",
                "Turquoise gemstone":"e12",
                "Turquoise seashells":"e12",
                "Cyan swimming pool":"e13",
                "Cyan sky":"e13",
                "Blue Topaz Gemstone":"e14",
                "Blue morpho butterfly":"e14"
        ]
    }
    
    func colorName() -> [String]{
        return [
        "a1",
        "a2",
        "a3",
        "a4",
        "a5",
        "a6",
        "a7",
        "a8",
        "a9",
        "a10",
        "a11",
        "a12",
        "a13",
        "a14",
        "b1",
        "b2",
        "b3",
        "b4",
        "b5",
        "b6",
        "b7",
        "b8",
        "b9",
        "b10",
        "b11",
        "b12",
        "b13",
        "b14",
        "c1",
        "c2",
        "c3",
        "c4",
        "c5",
        "c6",
        "c7",
        "c8",
        "c9",
        "c10",
        "c11",
        "c12",
        "c13",
        "c14",
        "d1",
        "d2",
        "d3",
        "d4",
        "d5",
        "d6",
        "d7",
        "d8",
        "d9",
        "d10",
        "d11",
        "d12",
        "d13",
        "d14",
        "e1",
        "e2",
        "e3",
        "e4",
        "e5",
        "e6",
        "e7",
        "e8",
        "e9",
        "e10",
        "e11",
        "e12",
        "e13",
        "e14"
    ]
    }
    
    // MARK: Not Needed
    func colorPallette() -> [Color] {
        return [
            Color("a1"),
            Color("a2"),
            Color("a3"),
            Color("a4"),
            Color("a5"),
            Color("a6"),
            Color("a7"),
            Color("a8"),
            Color("a9"),
            Color("a10"),
            Color("a11"),
            Color("a12"),
            Color("a13"),
            Color("a14"),
            Color("b1"),
            Color("b2"),
            Color("b3"),
            Color("b4"),
            Color("b5"),
            Color("b6"),
            Color("b7"),
            Color("b8"),
            Color("b9"),
            Color("b10"),
            Color("b11"),
            Color("b12"),
            Color("b13"),
            Color("b14"),
            Color("c1"),
            Color("c2"),
            Color("c3"),
            Color("c4"),
            Color("c5"),
            Color("c6"),
            Color("c7"),
            Color("c8"),
            Color("c9"),
            Color("c10"),
            Color("c11"),
            Color("c12"),
            Color("c13"),
            Color("c14"),
            Color("d1"),
            Color("d2"),
            Color("d3"),
            Color("d4"),
            Color("d5"),
            Color("d6"),
            Color("d7"),
            Color("d8"),
            Color("d9"),
            Color("d10"),
            Color("d11"),
            Color("d12"),
            Color("d13"),
            Color("d14"),
            Color("e1"),
            Color("e2"),
            Color("e3"),
            Color("e4"),
            Color("e5"),
            Color("e6"),
            Color("e7"),
            Color("e8"),
            Color("e9"),
            Color("e10"),
            Color("e11"),
            Color("e12"),
            Color("e13"),
            Color("e14")
        ]
    }
}
